version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: plataforma-seguros-db
    environment:
      POSTGRES_DB: db_plataforma_seguros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_plataforma_seguros_data:/var/lib/postgresql/data

volumes:
  db_plataforma_seguros_data: