// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proposta.Infrastructure;

#nullable disable

namespace Proposta.Infrastructure.Migrations
{
    [DbContext(typeof(PropostaDbContext))]
    [Migration("20260502001731_ResetPublic")]
    partial class ResetPublic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proposta.Domain.Entities.PropostaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Propostas", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ClienteNome = "João Silva",
                            CriadaEm = new DateTime(2026, 5, 2, 0, 17, 30, 285, DateTimeKind.Utc).AddTicks(1905),
                            StatusId = 1,
                            Valor = 1200m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClienteNome = "Maria Oliveira",
                            CriadaEm = new DateTime(2026, 5, 2, 0, 17, 30, 285, DateTimeKind.Utc).AddTicks(1911),
                            StatusId = 2,
                            Valor = 2300m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ClienteNome = "Ana Luiza",
                            CriadaEm = new DateTime(2026, 5, 2, 0, 17, 30, 285, DateTimeKind.Utc).AddTicks(1914),
                            StatusId = 3,
                            Valor = 2300m
                        });
                });

            modelBuilder.Entity("Proposta.Domain.Entities.PropostaStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PropostaStatus", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "EmAnalise"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aprovada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rejeitada"
                        });
                });

            modelBuilder.Entity("Proposta.Domain.Entities.PropostaEntity", b =>
                {
                    b.HasOne("Proposta.Domain.Entities.PropostaStatusEntity", "StatusReference")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusReference");
                });
#pragma warning restore 612, 618
        }
    }
}
